Repository leapfrogtechnology/LF-Sports, pull requests merged in 2018-02, with the labels that each got.

#12 SPORTS-21 Initial project setup for front-end application and folder structure
  chess/frontend/.babelrc
  chess/frontend/.editorconfig
  chess/frontend/package.json
  chess/frontend/public/css/style.css
  chess/frontend/public/images/.gitkeep
  chess/frontend/public/index.html
  chess/frontend/public/js/.gitkeep
  chess/frontend/src/component/Header/.gitkeep
  chess/frontend/src/component/admin/.gitkeep
  chess/frontend/src/component/common/.gitkeep
  chess/frontend/src/constant/.gitkeep
  chess/frontend/src/index.js
  chess/frontend/src/routes.js
  chess/frontend/src/service/.gitkeep
  chess/frontend/src/util/.gitkeep
  chess/frontend/webpack.config.js
Labels: enhancement, urgent

#11 SPORTS-6 > SPORTS-22 Create an API to create a new tournament
  chess/backend/package.json
  chess/backend/src/config/knex.ts
  chess/backend/src/constants/tables.ts
  chess/backend/src/controllers/tournament.ts
  chess/backend/src/errors/ChessError.ts
  chess/backend/src/errors/Error.ts
  chess/backend/src/errors/NoRowUpdatedError.ts
  chess/backend/src/errors/NotFoundError.ts
  chess/backend/src/filters/tournament.ts
  chess/backend/src/index.ts
  chess/backend/src/middlewares/genericErrorHandler.ts
  chess/backend/src/middlewares/index.ts
  chess/backend/src/migrations/20180118074819_create_table_tournament.ts
  chess/backend/src/migrations/20180118075605_create_table_player.ts
  chess/backend/src/migrations/20180118203058_create_table_round.ts
  chess/backend/src/migrations/20180118215553_create_tournament_category_table.ts
  chess/backend/src/migrations/20180118224909_create_table_tournament_player.ts
  chess/backend/src/migrations/20180118225059_create_match_table.ts
  chess/backend/src/migrations/20180203201544_create_table_fixture_status.ts
  chess/backend/src/migrations/20180203201744_create_table_winning_method.ts
  chess/backend/src/migrations/20180203202034_create_table_fixture.ts
  chess/backend/src/models/tournament.ts
  chess/backend/src/routes.ts
  chess/backend/src/services/tournament.ts
  chess/backend/src/validators/paramsValidator.ts
  chess/backend/src/validators/tournament.ts
  chess/backend/yarn.lock
Labels: new feature

#15 SPORTS-43 Update docker to run frontend
  frontend/package.json
  frontend/webpack.config.js
Labels: bug

#16 SPORTS-43 Enable hot-reload-modules in webpack
  frontend/webpack.config.js
Labels: bug

#17 SPORTS-23 Add an API to update tournament details
  backend/src/controllers/tournamentController.ts
  backend/src/middlewares/v1/tournamentMiddlewares.ts
  backend/src/routes/v1/tournamentRoutes.ts
  backend/src/services/tournamentService.ts
Labels: enhancement, new feature

#20 SPORTS-44 Add login page
  frontend/public/assets/css/style.css
  frontend/public/assets/images/.gitkeep
  frontend/public/assets/images/sports-logo.png
  frontend/src/assets/sass/_shame.scss
  frontend/src/assets/sass/base/_base.scss
  frontend/src/assets/sass/base/_manifest.scss
  frontend/src/assets/sass/libs/_manifest.scss
  frontend/src/assets/sass/modules/_login.scss
  frontend/src/assets/sass/modules/_manifest.scss
  frontend/src/assets/sass/modules/_site.scss
  frontend/src/assets/sass/states/_manifest.scss
  frontend/src/assets/sass/states/_print.scss
  frontend/src/assets/sass/states/_states.scss
  frontend/src/assets/sass/style.scss
  frontend/src/assets/sass/utilities/_config.scss
  frontend/src/assets/sass/utilities/_helpers.scss
  frontend/src/assets/sass/utilities/_manifest.scss
  frontend/src/assets/sass/utilities/_utilities.scss
  frontend/src/component/auth/Login.js
  frontend/src/component/auth/LoginForm.js
  frontend/src/component/auth/LoginHeader.js
  frontend/src/component/auth/index.js
  frontend/src/index.js
Labels: good first issue, new feature

#23 SPORTS-51 Prepare a defined format for API response
  backend/src/constants/messages.ts
  backend/src/controllers/tournamentController.ts
  backend/src/middlewares/genericErrorHandler.ts
  backend/src/services/tournamentService.ts
Labels: enhancement

#24 SPORTS-48 Add tournament tree structure
  docker-compose.yml
  frontend/package.json
  frontend/public/assets/css/style.css
  frontend/public/assets/images/dummy-image.jpg
  frontend/src/assets/sass/base/_base.scss
  frontend/src/assets/sass/modules/_card.scss
  frontend/src/assets/sass/modules/_login.scss
  frontend/src/assets/sass/modules/_manifest.scss
  frontend/src/assets/sass/modules/_site.scss
  frontend/src/assets/sass/modules/_tree.scss
  frontend/src/assets/sass/states/_manifest.scss
  frontend/src/assets/sass/states/_print.scss
  frontend/src/assets/sass/utilities/_config.scss
  frontend/src/assets/sass/utilities/_helpers.scss
  frontend/src/assets/sass/utilities/_manifest.scss
  frontend/src/assets/sass/utilities/_utilities.scss
  frontend/src/components/Routes.js
  frontend/src/components/tournament/tree/index.js
  frontend/src/components/tournament/tree/layers/FixtureRow.js
  frontend/src/components/tournament/tree/layers/Layer.js
  frontend/src/components/tournament/tree/layers/LayerHeader.js
  frontend/src/components/tournament/tree/layers/Playoff.js
  frontend/src/components/tournament/tree/layers/RoundFixtures.js
  frontend/src/components/tournament/tree/layers/Winner.js
  frontend/src/components/tournament/tree/treeCard/MatchTime.js
  frontend/src/components/tournament/tree/treeCard/Player.js
  frontend/src/components/tournament/tree/treeCard/PlayerPhoto.js
  frontend/src/components/tournament/tree/treeCard/index.js
  frontend/src/constants/constants.js
  frontend/src/constants/rounds.js
  frontend/src/constants/routes.js
  frontend/src/index.js
  frontend/src/utils/getImagesFromFixtures.js
  frontend/src/utils/routerHistory.js
  frontend/yarn.lock
Labels: new feature

#25 SPORTS-50 Make basic layout for fixtures and results
  docker-compose.yml
  frontend/public/assets/images/image.jpg
  frontend/src/assets/sass/base/_base.scss
  frontend/src/assets/sass/modules/_date.scss
  frontend/src/assets/sass/modules/_fixture.scss
  frontend/src/assets/sass/modules/_header.scss
  frontend/src/assets/sass/modules/_login.scss
  frontend/src/assets/sass/modules/_manifest.scss
  frontend/src/assets/sass/modules/_player.scss
  frontend/src/assets/sass/modules/_time.scss
  frontend/src/assets/sass/modules/_title.scss
  frontend/src/assets/sass/modules/_user.scss
  frontend/src/assets/sass/utilities/_config.scss
  frontend/src/assets/sass/utilities/_helpers.scss
  frontend/src/assets/sass/utilities/_utilities.scss
  frontend/src/components/Header/.gitkeep
  frontend/src/components/Routes.js
  frontend/src/components/auth/Login.js
  frontend/src/components/common/.gitkeep
  frontend/src/components/commons/date/Dates.js
  frontend/src/components/commons/date/index.js
  frontend/src/components/commons/header/.gitkeep
  frontend/src/components/commons/header/Header.js
  frontend/src/components/commons/header/index.js
  frontend/src/components/commons/title/Title.js
  frontend/src/components/commons/title/index.js
  frontend/src/components/fixture/Fixture.js
  frontend/src/components/fixture/index.js
  frontend/src/components/player/Player.js
  frontend/src/components/player/index.js
  frontend/src/components/time/Time.js
  frontend/src/components/time/index.js
  frontend/src/components/user/Home.js
  frontend/src/components/user/User.js
  frontend/src/components/user/index.js
  frontend/src/index.js
Labels: do not merge, new feature, wip

#26 SPORTS-54 Re-arrange the folder structure
  frontend/src/components/Routes.js
  frontend/src/components/commons/dates/Dates.js
  frontend/src/components/commons/dates/index.js
  frontend/src/components/fixture/index.js
  frontend/src/components/tournament/fixtureOverview/FixtureOverview.js
  frontend/src/components/tournament/fixtureOverview/fixtureCard/FixtureCard.js
  frontend/src/components/tournament/fixtureOverview/fixtureCard/index.js
  frontend/src/components/tournament/fixtureOverview/index.js
  frontend/src/components/tournament/fixtureOverview/player/Player.js
  frontend/src/components/tournament/fixtureOverview/player/index.js
  frontend/src/components/tournament/fixtureOverview/time/Time.js
  frontend/src/components/tournament/fixtureOverview/time/index.js
  frontend/src/components/tournament/tree/Tree.js
  frontend/src/components/tournament/tree/index.js
  frontend/src/components/user/index.js
  frontend/src/constants/routes.js
Labels: enhancement

#27 SPORTS-59 Add seeds for round and user_role tables
  backend/src/constants/fixedModelValues.ts
  backend/src/constants/tables.ts
  backend/src/seeds/seed_round_table.ts
  backend/src/seeds/seed_user_role_table.ts
  docker-compose.yml
Labels: enhancement, urgent

#32 SPORTS-70 Create webpack config for production
  frontend/package.json
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: enhancement

#31 SPORTS-68 Move all middlewares to routes
  backend/src/controllers/apiController.ts
  backend/src/controllers/authController.ts
  backend/src/controllers/categoryController.ts
  backend/src/controllers/homeController.ts
  backend/src/controllers/tournamentController.ts
  backend/src/controllers/userController.ts
  backend/src/controllers/userRoleController.ts
  backend/src/index.ts
  backend/src/middlewares/index.ts
  backend/src/middlewares/v1/authMiddlewares.ts
  backend/src/middlewares/v1/categoryMiddlewares.ts
  backend/src/middlewares/v1/index.ts
  backend/src/middlewares/v1/tournamentMiddlewares.ts
  backend/src/middlewares/v1/userMiddlewares.ts
  backend/src/middlewares/v1/userRoleMiddlewares.ts
  backend/src/routes/v1/authRoutes.ts
  backend/src/routes/v1/categoryRoutes.ts
  backend/src/routes/v1/tournamentRoutes.ts
  backend/src/routes/v1/userRoleRoutes.ts
  backend/src/routes/v1/userRoutes.ts
Labels: enhancement

#33 SPORTS-69 Add pre-commit hooks of prettier and es-lint
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/components/Routes.js
  frontend/src/components/auth/Login.js
  frontend/src/components/commons/dates/Dates.js
  frontend/src/components/commons/header/Header.js
  frontend/src/components/commons/title/Title.js
  frontend/src/components/tournament/fixtureOverview/FixtureOverview.js
  frontend/src/components/tournament/fixtureOverview/fixtureCard/FixtureCard.js
  frontend/src/components/tournament/fixtureOverview/player/Player.js
  frontend/src/components/tournament/fixtureOverview/time/Time.js
  frontend/src/components/tournament/tree/Tree.js
  frontend/src/components/tournament/tree/layers/FixtureRow.js
  frontend/src/components/tournament/tree/layers/Layer.js
  frontend/src/components/tournament/tree/layers/LayerHeader.js
  frontend/src/components/tournament/tree/layers/Playoff.js
  frontend/src/components/tournament/tree/layers/RoundFixtures.js
  frontend/src/components/tournament/tree/layers/Winner.js
  frontend/src/components/tournament/tree/treeCard/MatchTime.js
  frontend/src/components/tournament/tree/treeCard/Player.js
  frontend/src/components/tournament/tree/treeCard/PlayerPhoto.js
  frontend/src/components/tournament/tree/treeCard/index.js
  frontend/src/constants/constants.js
  frontend/src/constants/rounds.js
  frontend/src/index.js
  frontend/src/utils/routerHistory.js
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: enhancement

#34 SPORTS-53 Enable user to login and logout
  frontend/.babelrc
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/assets/sass/modules/_login.scss
  frontend/src/components/Routes.js
  frontend/src/components/admin/Test.js
  frontend/src/components/auth/Login.js
  frontend/src/components/commons/Navigation.js
  frontend/src/components/commons/Toaster.js
  frontend/src/components/hocs/PrivateRoute.js
  frontend/src/components/hocs/redirectIfAuthenticated.js
  frontend/src/components/tournament/fixtureOverview/player/Player.js
  frontend/src/components/tournament/tree/layers/Layer.js
  frontend/src/components/tournament/tree/treeCard/Player.js
  frontend/src/components/tournament/tree/treeCard/PlayerPhoto.js
  frontend/src/components/tournament/tree/treeCard/index.js
  frontend/src/constants/apiUrls.js
  frontend/src/constants/constants.js
  frontend/src/constants/errorMessages.js
  frontend/src/constants/routes.js
  frontend/src/services/authServices/login.js
  frontend/src/services/authServices/logout.js
  frontend/src/services/authServices/refreshAccessToken.js
  frontend/src/services/userServices/fetchUsers.js
  frontend/src/utils/axiosInstance.js
  frontend/src/utils/getAuthDetails.js
  frontend/src/utils/getImagesFromFixtures.js
  frontend/src/utils/routerHistory.js
  frontend/yarn.lock
Labels: new feature :new:

#37 SPORTS-72 Add propType validation for react components
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/components/Routes.js
  frontend/src/components/auth/Login.js
  frontend/src/components/commons/Navigation.js
  frontend/src/components/commons/Toaster.js
  frontend/src/components/hocs/PrivateRoute.js
  frontend/src/components/hocs/redirectIfAuthenticated.js
  frontend/src/components/tournament/fixtureOverview/fixtureCard/FixtureCard.js
  frontend/src/components/tournament/tree/Tree.js
  frontend/src/components/tournament/tree/layers/FixtureRow.js
  frontend/src/components/tournament/tree/layers/Layer.js
  frontend/src/components/tournament/tree/layers/LayerHeader.js
  frontend/src/components/tournament/tree/layers/Playoff.js
  frontend/src/components/tournament/tree/layers/RoundFixtures.js
  frontend/src/components/tournament/tree/layers/Winner.js
  frontend/src/components/tournament/tree/treeCard/MatchTime.js
  frontend/src/components/tournament/tree/treeCard/Player.js
  frontend/src/components/tournament/tree/treeCard/PlayerPhoto.js
  frontend/src/components/tournament/tree/treeCard/index.js
  frontend/yarn.lock
  to-be-removed/frontend/.gitignore
  to-be-removed/frontend/README.md
  to-be-removed/frontend/package.json
  to-be-removed/frontend/public/favicon.ico
  to-be-removed/frontend/public/index.html
  to-be-removed/frontend/public/manifest.json
  to-be-removed/frontend/src/App.css
  to-be-removed/frontend/src/App.js
  to-be-removed/frontend/src/App.test.js
  to-be-removed/frontend/src/assets/logo.svg
  to-be-removed/frontend/src/index.css
  to-be-removed/frontend/src/index.js
  to-be-removed/frontend/src/registerServiceWorker.js
  to-be-removed/frontend/yarn.lock
Labels: enhancement
