Repository leapfrogtechnology/LF-Sports, pull requests merged in 2018-03, with the labels that each got.

#38 SPORTS-71 Add APIs to add/edit/get/delete fixtures.
  backend/src/constants/messages.ts
  backend/src/controllers/chessFixtureController.ts
  backend/src/domain/ChessFixtureInterface.ts
  backend/src/errors/AlreadyExistsError.ts
  backend/src/errors/BadRequestError.ts
  backend/src/migrations/20180222135545_alter_table_user_add_email.ts
  backend/src/migrations/20180302104650_alter_table_chess_fixtures_rename_team_to_player.ts
  backend/src/models/chessFixture.ts
  backend/src/routes/v1/chessFixtureRoutes.ts
  backend/src/routes/v1/index.ts
  backend/src/schemas/chessFixtureSchema.ts
  backend/src/services/chessFixtureService.ts
  backend/src/validators/chessFixtureValidator.ts
Labels: enhancement, new feature :new:

#36 SPORTS-2 As a user, I should be able to manage the tournaments
  frontend/.eslintrc.json
  frontend/package.json
  frontend/public/assets/images/leapfrog-logo.png
  frontend/public/index.html
  frontend/src/assets/sass/modules/_admin.scss
  frontend/src/assets/sass/modules/_card.scss
  frontend/src/assets/sass/modules/_manifest.scss
  frontend/src/assets/sass/modules/_user.scss
  frontend/src/assets/sass/utilities/_config.scss
  frontend/src/components/Routes.js
  frontend/src/components/admin/Admin.js
  frontend/src/components/admin/Test.js
  frontend/src/components/admin/actions/CreateTournament.js
  frontend/src/components/admin/index.js
  frontend/src/components/admin/tournamentList/TournamentList.js
  frontend/src/components/admin/tournamentList/index.js
  frontend/src/components/admin/tournamentModal/AddEditTournamentModal.js
  frontend/src/components/admin/tournamentModal/DeleteTournamentModal.js
  frontend/src/components/hocs/tournamentActions.js
  frontend/src/constants/apiUrls.js
  frontend/src/constants/constants.js
  frontend/src/constants/errorMessages.js
  frontend/src/index.js
  frontend/src/services/tournamentServices/tournamentServices.js
  frontend/src/services/userServices/fetchUsers.js
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: new feature :new:

#40 SPORTS-77 Add propType validation
  frontend/src/components/admin/Admin.js
  frontend/src/components/admin/actions/CreateTournament.js
  frontend/src/components/admin/index.js
  frontend/src/components/admin/tournamentList/TournamentList.js
  frontend/src/components/admin/tournamentList/index.js
  frontend/src/components/admin/tournamentModal/AddEditTournamentModal.js
  frontend/src/components/admin/tournamentModal/DeleteTournamentModal.js
  frontend/src/components/auth/Login.js
  frontend/src/components/commons/header/Header.js
  frontend/src/components/hocs/tournamentActions.js
  frontend/src/constants/rounds.js
  frontend/src/index.js
  frontend/src/utils/axiosInstance.js
Labels: enhancement

#41 SPORTS-73 Add navbar for admin
  frontend/public/assets/images/sports-logo.svg
  frontend/src/assets/sass/base/_base.scss
  frontend/src/assets/sass/modules/_manifest.scss
  frontend/src/assets/sass/modules/_navbar.scss
  frontend/src/assets/sass/utilities/_utilities.scss
  frontend/src/components/Routes.js
  frontend/src/components/commons/Navigation.js
  frontend/src/components/commons/navigation/AdminLeftNav.js
  frontend/src/components/commons/navigation/AdminNavigation.js
  frontend/src/components/commons/navigation/UserImage.js
  frontend/src/components/commons/navigation/UserLeftNav.js
  frontend/src/components/commons/navigation/UserNavigation.js
  frontend/src/components/commons/navigation/index.js
  frontend/src/components/hocs/PrivateRoute.js
  frontend/src/components/hocs/redirectIfAuthenticated.js
  frontend/src/components/hocs/withActiveRoute.js
  frontend/src/components/players/index.js
  frontend/src/constants/constants.js
  frontend/src/constants/routes.js
  frontend/webpack.config.js
Labels: new feature :new:

#42 SPORTS-75 Add docker-compose service for build and test frontend
  docker-compose.yml
  docker-compose/frontend/nginx.conf
  frontend/package.json
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: enhancement

#43 SPORTS-81 Show non-compressed images
  frontend/src/assets/sass/utilities/_utilities.scss
Labels: enhancement

#44 SPORTS-82 Edit production webpack config to load svg images
  frontend/webpack.config.prod.js
Labels: bug :bug:
